function esc(s){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
const CATEGORY_LINKS={'Electrical / NEC':'electrical/','HVAC':'hvac/','Mechanical Engineering':'mechanical/','Construction':'construction/','Finance':'finance/'};
const UNIT_PROFILES={'wire-size':{distance:{imperial:['ft',1],metric:['m',3.280839895013123]}},'voltage-drop':{distance:{imperial:['ft',1],metric:['m',3.280839895013123]}},'conduit-fill':{id:{imperial:['in',1],metric:['mm',25.4]}},'cfm':{length:{imperial:['ft',1],metric:['m',3.280839895013123]},width:{imperial:['ft',1],metric:['m',3.280839895013123]},height:{imperial:['ft',1],metric:['m',3.280839895013123]}}};
let UNIT_SYSTEM='imperial';
function unitProfile(slug,key){return UNIT_PROFILES[slug]?.[key]||null}
function calculatorHref(slug){return `/calculators/${encodeURIComponent(slug)}/`}
function card(category,title,slug,live){return `<a class="tool ${live?'':'soon'}" href="${live?calculatorHref(slug):'#'}"><span class="tag">${esc(category)}</span><h3>${esc(title)}</h3><p>${live?'Interactive calculator with formula, worked example and FAQs.':'Planned calculator — coming soon.'}</p><span class="tool-link">${live?'Open calculator →':'Coming soon'}</span></a>`}
function renderHome(){const cats=[['Electrical / NEC','⚡','Electrical calculations for conductor sizing, voltage drop, conduit and power.'],['HVAC','◫','Airflow, ventilation, ductwork and thermal calculations for HVAC workflows.'],['Mechanical Engineering','⚙','Machine-design calculations for bearings, drives, torque and speed.'],['Construction','▦','Concrete, steel, rebar, roofing and site-material calculations.'],['Finance','$','Mortgage, loan, interest, savings, growth, payoff and payment calculators for personal finance scenarios.']];document.getElementById('categoryGrid').innerHTML=cats.map(c=>`<a class="category category-link" href="${CATEGORY_LINKS[c[0]]}"><div class="icon">${c[1]}</div><h3>${c[0]}</h3><p>${c[2]}</p><span class="tool-link">Explore ${c[0]} →</span></a>`).join('');const items=PLANNED.map(([c,t,s])=>({category:c,title:t,slug:s,live:!!CALCULATORS[s]));const liveItems=items.filter(x=>x.live);document.getElementById('popularGrid').innerHTML=liveItems.map(x=>card(x.category,x.title,x.slug,true)).join('');document.getElementById('allGrid').innerHTML=items.filter(x=>!x.live).map(x=>card(x.category,x.title,x.slug,false)).join('')}
function fieldHtml(f){const [key,label,unit,type,extra,defaultVal]=f;const route=new URLSearchParams(location.search);const pathMatch=location.pathname.match(/\/calculators\/([^/]+)(?:\/index\.html)?\/?$/);const slug=route.get('slug')|| (pathMatch?decodeURIComponent(pathMatch[1]):'');const profile=unitProfile(slug,key);const displayUnit=profile?profile[UNIT_SYSTEM][0]:unit;let displayValue=defaultVal;if(profile&&type!=='select')displayValue=(Number(defaultVal)*profile[UNIT_SYSTEM][1]).toFixed(2).replace(/\.00$/,'');if(type==='select')return `<div class="field"><label for="${key}">${label}${displayUnit?' ('+displayUnit+')':''}</label><select id="${key}">${extra.map(o=>`<option ${o===defaultVal?'selected':''}>${o}</option>`).join('')}</select></div>`;return `<div class="field"><label for="${key}">${label}${displayUnit?' ('+displayUnit+')':''}</label><input id="${key}" type="number" step="any" min="0" value="${displayValue}"><small>${profile?`Enter ${displayUnit}. Values convert automatically.`:'Enter a positive value.'}</small></div>`}
function renderUnitControl(c){const wrap=document.getElementById('unitControl');if(!wrap)return;const slug=Object.keys(CALCULATORS).find(k=>CALCULATORS[k]===c);const hasUnits=!!UNIT_PROFILES[slug];wrap.hidden=!hasUnits;if(!hasUnits)return;wrap.innerHTML=`<div class="unit-toggle" role="group" aria-label="Unit system"><span>Units</span><button type="button" class="unit-option ${UNIT_SYSTEM==='imperial'?'active':''}" data-unit="imperial">Imperial</button><button type="button" class="unit-option ${UNIT_SYSTEM==='metric'?'active':''}" data-unit="metric">Metric</button></div>`;wrap.querySelectorAll('[data-unit]').forEach(btn=>btn.addEventListener('click',()=>{const old=UNIT_SYSTEM;UNIT_SYSTEM=btn.dataset.unit;try{localStorage.setItem('calcforge-unit-system',UNIT_SYSTEM)}catch(e){}for(const f of c.fields){const profile=unitProfile(slug,f[0]);const el=document.getElementById(f[0]);if(profile&&el&&f[3]!=='select'){const canonical=Number(el.value)/profile[old][1];el.value=(canonical*profile[UNIT_SYSTEM][1]).toFixed(2).replace(/\.00$/,'')}}document.getElementById('formFields').innerHTML='<div class="field-grid">'+c.fields.map(fieldHtml).join('')+'</div>';runCalculator(c,false);renderUnitControl(c)}))}
function runCalculator(c,track=true){const slug=Object.keys(CALCULATORS).find(k=>CALCULATORS[k]===c);const values={};for(const f of c.fields){const el=document.getElementById(f[0]);let value=f[3]==='select'?el.value:Number(el.value);const profile=unitProfile(slug,f[0]);if(profile&&f[3]!=='select')value=value/profile[UNIT_SYSTEM][1];values[f[0]]=value}if(Object.values(values).some(v=>v===''||Number.isNaN(v)||v===undefined))return;const r=c.calc(values);document.getElementById('result').innerHTML=`<strong>${esc(r.main)}</strong><span class="sub">${esc(r.sub||'')}</span>`;if(track&&window.CalcForgeAnalytics&&c)window.CalcForgeAnalytics.trackEvent('calculation_completed',{calculator_name:c.title,calculator_category:c.category,calculator_slug:slug,unit_system:UNIT_SYSTEM})}
try{const saved=localStorage.getItem('calcforge-unit-system');if(saved==='metric'||saved==='imperial')UNIT_SYSTEM=saved}catch(e){}
if(document.getElementById('categoryGrid')){if(document.querySelector('script[src="/finance-day2.js"]'))renderHome();else{const s=document.createElement('script');s.src='/finance-day2.js';s.onload=renderHome;document.head.appendChild(s)}}
