const CATEGORY_SEO={
 electrical:{name:'Electrical Calculators',category:'Electrical / NEC',title:'Electrical Calculators | Wire Size, Voltage Drop & Conduit Fill',description:'Free electrical calculators for wire size, voltage drop, conduit fill, ampacity, wire gauge, breaker sizing, transformer sizing and three-phase power. Practical tools with formulas, examples and NEC-focused assumptions.',intro:'Use CalcForge electrical calculators for practical conductor, voltage-drop, raceway-fill, ampacity, protection and power checks. The cluster covers common electrical search needs such as wire size, wire gauge, voltage drop, conduit fill and three-phase calculations, with related tools linked together for easier review.'},
 hvac:{name:'HVAC Calculators',category:'HVAC',title:'HVAC Calculators | CFM, Airflow & Ventilation Tools',description:'Free HVAC calculators for CFM, airflow and ventilation planning. Calculate room airflow from volume and air changes per hour with transparent formulas.',intro:'Use CalcForge HVAC calculators for quick airflow and ventilation estimates. These tools explain the relationship between room volume, air changes and CFM while clearly separating preliminary calculations from final HVAC design.'},
 mechanical:{name:'Mechanical Engineering Calculators',category:'Mechanical Engineering',title:'Mechanical Engineering Calculators | Bearings, Torque & More',description:'Free mechanical engineering calculators for bearing life and rotating-equipment calculations, with practical formulas, examples and assumptions.',intro:'Use CalcForge mechanical engineering calculators for transparent machine-design checks. The mechanical cluster focuses on practical relationships such as bearing rating life, load, speed, torque and other rotating-equipment calculations.'},
 construction:{name:'Construction Calculators',category:'Construction',title:'Construction Calculators | Concrete, Rebar, Steel & More',description:'Free construction calculators for concrete, rebar, steel weight, gravel, sand, roof pitch and stairs. Practical quantity and building calculations.',intro:'Use CalcForge construction calculators for material quantities and common building calculations. Each tool is intended to make estimating and checking easier while leaving project-specific code, waste and site assumptions visible.'}
};
function trackCategoryAnalytics(s,key){const payload={articleName:s.name,articleSlug:key,category:s.category,contentGroup:'Category Pages'};if(window.CalcForgeAnalytics){window.CalcForgeAnalytics.trackPage(payload);return}const script=document.createElement('script');script.src='../analytics.js';script.onload=function(){if(window.CalcForgeAnalytics)window.CalcForgeAnalytics.trackPage(payload)};document.head.appendChild(script)}
function renderCategory(){const key=document.body.dataset.category;const s=CATEGORY_SEO[key];if(!s)return;document.title=s.title;document.getElementById('metaDescription').content=s.description;document.getElementById('canonical').href=`https://calcforge.github.io/${key}/`;document.getElementById('ogTitle').content=s.title;document.getElementById('ogDescription').content=s.description;document.getElementById('categoryName').textContent=s.name;document.getElementById('categoryIntro').textContent=s.intro;const items=PLANNED.filter(x=>x[0]===s.category);document.getElementById('categoryTools').innerHTML=items.map(x=>{const live=!!CALCULATORS[x[2]];return `<a class="tool ${live?'':'soon'}" href="${live?`../calculator.html?slug=${x[2]}`:'#'}"><span class="tag">${esc(s.name)}</span><h2>${esc(x[1])}</h2><p>${live?'Live calculator with formula, example, FAQs and related tools.':'Planned tool — the category cluster already identifies it for future expansion.'}</p><span class="tool-link">${live?'Open calculator →':'Coming soon'}</span></a>`}).join('');document.getElementById('categoryBreadcrumb').textContent=s.name;document.getElementById('categorySchema').textContent=JSON.stringify({'@context':'https://schema.org','@type':'CollectionPage','name':s.name,'url':`https://calcforge.github.io/${key}/`,'description':s.description,'isPartOf':{'@type':'WebSite','name':'CalcForge','url':'https://calcforge.github.io/'}});trackCategoryAnalytics(s,key)}
renderCategory();
